package com.auroraworld.toypic.db;

public enum DBRequestType {
    JOIN,
    JOIN_EMAIL,
    EMAIL_LOGIN,
    CREATE_CHILD,
    GET_CHILD,
    UPDATE_CHILD,
    DELETE_CHILD,
    GET_ALL_GOODS,
    GET_GOODS_INFO,
    GET_REVIEW_LIST,
    GET_MY_REVIEW,
    DELETE_REVIEW,
    INSERT_REVIEW,
    GET_ALL_BRAND,
    GET_EVALUATE_GOODS,
    INSERT_EVALUATE_GOODS,
    GET_FAVORITE_KEYWORD,
    GET_RECENT_KEYWORD,
    DELETE_RECENT_KEYWORD,
    SEARCH_GOODS,
    GET_CUSTOM_GOODS,
    LIKE,
    TEST
}
