package com.wellstech.tpictest.db;

public enum DBRequestType {
    JOIN,
    CREATE_CHILD,
    GET_CHILD,
    UPDATE_CHILD,
    DELETE_CHILD,
    GET_ALL_GOODS,
    GET_GOODS_INFO,
    GET_REVIEW_LIST,
    INSERT_REVIEW,
    GET_ALL_BRAND,
    GET_EVALUATE_GOODS,
    INSERT_EVALUATE_GOODS,
    GET_FAVORITE_KEYWORD,
    GET_RECENT_KEYWORD,
    DELETE_RECENT_KEYWORD,
    SEARCH_GOODS,
    LIKE,
    TEST
}
